#!/bin/bash

python3 manage.py makemigrations users --settings=tmex_main.settings.production;
python3 manage.py makemigrations sc --settings=tmex_main.settings.production;
python3 manage.py makemigrations --settings=tmex_main.settings.production;
python3 manage.py migrate --settings=tmex_main.settings.production;
python3 manage.py pop --settings=tmex_main.settings.production;
